# Workflow search - detail block
# For a configuration example see "RA Operator.yaml".
# Setting undef here hides the grey box on the right
# Do not set this node to use the builtin default
wfdetails: ~

