global:
    realm: democa

    # Servername can be set for all workflows/operations here at once or
    # for each one below. If neither one is set, simpleenroll/simplerenroll
    # use the calabel from the URL as server name
    # servername: default

    # Set to 1 if you want to serve EST over plain HTTP
    # insecure: 0

logger:
    # Log level: overrides system.logger.level
    #   "DEBUG" MIGHT disclose sensitive user input data.
    #   "TRACE" WILL dump unfiltered communication.
    #level: INFO

auth:
    stack: _System

output:
    # To ease debugging and error handling you can set the workflowid
    # transactionid and workflow error code as HTTP headers.
    # Only supported value for now is "all"
    headers: all

# You can set env vars and workflow for each operation
# but the defaults should be ok

#simpleenroll:
#    workflow: certificate_enroll
#    env:
#     - server
#     - signer_cert

#simplereenroll:
#    workflow: certificate_enroll
#    env:
#     - server
#     - client_ip
#     - signer_cert
#     - signer_dn

#csrattrs:
#    workflow: est_csrattrs
#    env:
#     - client_ip

#cacerts:
#    workflow: est_cacerts
#    env:
#     - client_ip

#simplerevoke:
#    workflow: certificate_revoke
#    env:
#     - server
#     - signer_cert
#    preset:
#        reason_code: unspecified
